//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cdws.Edmx
{
    using System;
    using System.Collections.Generic;
    
    public partial class Total
    {
        public int Id { get; set; }
        public Nullable<System.DateTime> time { get; set; }
        public Nullable<int> reqStatus { get; set; }
        public string count { get; set; }
        public string fundTotal { get; set; }
    }
}
